### ISSUE TITLE
Add building of E-book formats to the toolchain and provide E-book builds

### ISSUE THREAD

**Issue by cryzed** [rust-lang/rust-by-example#684] opened 2015-12-30 13:54 UTC
Hey, it would be awesome if you could also provide [E-Book formats](https://github.com/GitbookIO/gitbook#output-formats). I know that one of Rust by Example's biggest feature is the "run example" feature, but it'd be naive to assume that's the only way people use it. I for example really like to just glance at the very well-documented code snippets along with the description and learn that way. Having this on my Kindle would be neat.

Same by the way goes for [The Rust Programming Language Book](https://github.com/steveklabnik/rustbook), although some unofficial builds [are available](https://killercup.github.io/trpl-ebook/) (which I assume are outdated by now).

I tried to run the provided Rust code to generate the `SUMMARY.md` on my own, but the paths within the executable seem to be hardcoded for *nix environments (or I'm doing something else wrong):

```
flow_control: os error
scope: os error
custom_types: os error
```

This is why it would be great if you could simply add building the E-book formats to the toolchain and keep them up-to-date with the website.

**Comment by steveklabnik** [comment] 2015-12-30 14:14
We have an issue open in the main repo about the official book already :)

I'm not sure what the best way to provide these would be. Maybe we can have Travis do it somehow?

**Comment by mdinger** [comment] 2015-12-30 16:09
I think I tried this once before but it didn't work for some reason. I would've been interested in the pdf but I don't think I put a lot of time into it. Also, we're on an older version of gitbook so the instructions provided there might not be accurate anymore.

**Comment by mdinger** [comment] 2015-12-30 16:52
It does work. You go [here](http://calibre-ebook.com/download_linux), install the binary and tell gitbook to generate the pdf and ebooks. However, it royally botches the runnable examples when they're displayed.

![ebook](https://cloud.githubusercontent.com/assets/4156987/12053823/d9bc6902-aeea-11e5-986d-a397a5451355.png)

To make this work, you'd probably have to create a stage2 just for exports like this and disable the special formatting and such that the runnable examples require. Then it would probably work correctly. Seems like a nuisance.

**Comment by steveklabnik** [comment] 2017-09-14 20:07
since we've ported to mdBook, this is now a duplicate of https://github.com/azerupi/mdBook/issues/88

**Closed by steveklabnik** 2017-09-14 20:07 UTC

**Comment by hustcer** [comment] 2021-12-20 05:53
I have just made a epub version of `Rust by Example`, if anyone need it just download from here: https://github.com/hustcer/open-books/blob/main/Rust%20By%20Examples.epub
