### ISSUE TITLE
Variable bindings doesn't show warning message

### ISSUE THREAD

**Issue by GordanZovko** [rust-lang/rust-by-example#1332] opened 2020-04-13 10:04 UTC
`https://doc.rust-lang.org/stable/rust-by-example/variable_bindings.html`

Running default code in browser doesn't show a warning message for variable without underscore prefix.

**Comment by ErikSwan** [comment] 2020-05-23 02:38
I believe this is a duplicate of #1328.

**Closed** 2022-04-08 09:43 UTC
