### ISSUE TITLE
Rust by Example in PDF

### ISSUE THREAD

**Issue by afiskon** [rust-lang/rust-by-example#270] opened 2014-11-06 19:54 UTC
It would be great if Rust by Example would be available in PDF. You can just create a single HTML-page with whole book content, in this case anyone could create a PDF using Print Friendly & PDF plugin for Google Chrome and other solutions.

**Comment by mvallerie** [comment] 2015-01-15 05:15
+1

Probably not an ideal workaround (neither for users, nor for rust maintainers, nor for rust servers, sorry about that) but this basically works (expect some minor issues anyway, and it's NOT single page) :

wget -r -k -np http://rustbyexample.com/

**Comment by milanaleksic** [comment] 2015-01-27 10:30
+1
For newcomers that wish to dive in, this seems like a reasonable approach.
Not only PDF, though - I'd recommend making MOBI and EPUB as well...

**Comment by funivan** [comment] 2015-02-05 14:54
+1
 `wget -r -k -np http://rustbyexample.com/` is good solition but sometimes pdf/mobi/epub is better

**Comment by Anachron** [comment] 2015-04-22 00:53
Just created this little script to download & update the most important rust-docs:

```bash
#!/bin/bash

wget -r -k -np http://rustbyexample.com/
wget -r -k -np -X "book,src,std" https://doc.rust-lang.org/reference.html
wget -r -k -np https://doc.rust-lang.org/nightly/rustc/
```

**Comment by mdinger** [comment] 2015-04-22 01:04
FYI: the [book: installation](http://doc.rust-lang.org/1.0.0-beta.2/book/installing-rust.html)

> This installer also installs a copy of the documentation locally, so you can read it offline. On UNIX systems, /usr/local/share/doc/rust is the location. On Windows, it's in a share/doc directory, inside wherever you installed Rust to.

**Comment by filib** [comment] 2015-05-12 12:26
:+1:

**Comment by a0x** [comment] 2016-04-17 04:58
I've been dealing with this issue in this whole morning, and I found something.
After `make book`, in the `stage/` dir, there'are all markdown files, which are well constructed in the way of the table of contents.
![_20160417125350](https://cloud.githubusercontent.com/assets/3829546/14585141/1a6cfdd4-049c-11e6-9452-d47870c162d4.png)


So things become how to generate a single PDF file via a group of markdown files.

**Comment by a0x** [comment] 2016-04-17 06:48
I'm still working on this issue, in progress, but met a problem.

In the source file, `rust-playpen` is used to display and run the code in web page, and it is used as a plugin written in `book.json` file. 

Unfortunately, when compiling into ebook on Gitbook website, it says missing `gitbook-plugin-rust-playpen`, and of course there is no `gitbook-plugin-rust-playpen`.  You can check it [here](https://www.gitbook.com/book/a0x/rust-by-example/build/571329f3fa8d2b0f00832d82).

Then I tried to remove this plugin and did recompile, another [error](https://www.gitbook.com/book/a0x/rust-by-example/build/57132e2f295bcd100062ec5c) occurred, I checked the detail and only found to rewrite all the real rust code blocks(which could run in the web page) in this project, and that's a mass work. 

So, before I start this mass, is there any way to figure this out?

**Comment by a0x** [comment] 2016-04-17 08:11
After above, I met another error while building ebooks online:
```
Template render error: (/tmp/book/std_misc/arg/matching.md)
  Error: filter not found: decrease (In file 'std_misc/arg/matching.md')
```

What does this mean?

**Comment by a0x** [comment] 2016-04-17 09:19
Yes, I've made it, even just the first step. You can check it [here](https://www.gitbook.com/book/a0x/rust-by-example/details).

But there's still some work. In the source files, every code block is written in: 
```html
<div id="active-code">
<button class="btn btn-primary" type="button" id="run-code">Run</button>
<button class="btn btn-primary" type="button" id="reset-code">Reset</button>
<div id="editor">
......
</div>
<div id="result"></div>
</div>
```
which cannot be recognized as code block format. I have to solve this issue. Do you have any suggestions?

**Comment by mdinger** [comment] 2016-04-17 16:06
I don't really know but fwiw, work to support extra features like that has
mostly been put off until rbe switches to mdbook. Work might already be
underway in mdbook to export PDF but I'm not sure. Regardless, work to
support inline, runnable, code blocks was almost complete and was one of
the major roadblocks hindering adoption.

I wouldn't put a lot of work into this when we're just intending to migrate
as soon as possible.

**Comment by DanielSherlock** [comment] 2016-07-13 22:16
This is still open, so if people are still looking for a .pdf/.epub/.mobi then try the right hand side of [this page](https://www.gitbook.com/book/a0x/rust-by-example/details), just under the big blue "read" button. I had a quick look over the .pdf, and it seems to be the same content, though obviously the code isn't editable.

**Comment by a0x** [comment] 2016-07-20 03:34
@DanielSherlock Yes, this is what I did months ago when I had pretty much free time. However, I'm afraid that I don't have much time to maintain this e-book these days. 

As I mentioned above, code highlighting isn't working due to the `<div>` problem, and all you need is just a wrapper to convert `<div class="active-code"></div>` into `<code></code>'.

And of course, in static HTML pages, as well as epub/pdf files, you cannot edit those code blocks.

**Comment by steveklabnik** [comment] 2017-09-14 20:07
Now that we've ported to mdBook, this is a duplicate of https://github.com/azerupi/mdBook/issues/88

**Closed by steveklabnik** 2017-09-14 20:07 UTC
Labels: enhancement

**Comment by hustcer** [comment] 2021-12-20 05:52
I have just made a epub version of `Rust by Example`, if anyone need it just download from here: https://github.com/hustcer/open-books/blob/main/Rust%20By%20Examples.epub
